# Generated by Django 6.0.5 on 2026-05-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcalBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('source', models.CharField(default='Airbnb', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_blocks', to='properties.property')),
            ],
            options={
                'verbose_name': 'Bloqueo iCal',
                'verbose_name_plural': 'Bloqueos iCal',
            },
        ),
    ]
