# Generated by Django 6.0.5 on 2026-05-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ical_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icalblock',
            options={},
        ),
        migrations.RemoveField(
            model_name='icalblock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='icalblock',
            name='source',
        ),
        migrations.AddField(
            model_name='icalblock',
            name='is_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='icalblock',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
