# Generated by Django 6.0.5 on 2026-05-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('airbnb_ical_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
