# Generated by Django 6.0.5 on 2026-05-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=5),
        ),
    ]
