# Generated by Django 6.0.5 on 2026-07-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='airbnb_listing_name',
            field=models.CharField(blank=True, help_text="Nombre exacto del anuncio como aparece en el CSV de Airbnb (columna 'Anuncio')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
    ]
