# Generated by Django 6.0.5 on 2026-05-22 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_remove_booking_net_income_and_more'),
        ('properties', '0003_property_commission_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerFinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=10)),
                ('category', models.CharField(choices=[('late_checkout', 'Late Checkout'), ('early_checkin', 'Early Check-in'), ('repair', 'Reparación'), ('supply', 'Insumos'), ('guest_compensation', 'Compensación Huésped'), ('utilities', 'Servicios'), ('maintenance', 'Mantención'), ('other', 'Otro')], max_length=30)),
                ('amount', models.IntegerField()),
                ('owner_impact', models.CharField(choices=[('full_owner', '100% Propietario'), ('full_admin', '100% Staykeeper'), ('mixed', 'Mixto (aplica comisión)')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_transactions', to='bookings.booking')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_transactions', to='properties.property')),
            ],
            options={
                'verbose_name': 'Transacción Financiera',
                'verbose_name_plural': 'Transacciones Financieras',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='OwnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado')], default='pending', max_length=10)),
                ('scheduled_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='Transferencia Bancaria', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='bookings.booking')),
                ('property_charges', models.ManyToManyField(blank=True, related_name='included_in_payouts', to='owner_finances.ownerfinancialtransaction')),
            ],
            options={
                'verbose_name': 'Pago a Propietario',
                'verbose_name_plural': 'Pagos a Propietarios',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
