# Generated by Django 6.0.5 on 2026-05-12 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(max_length=50, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_income', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.guest')),
            ],
        ),
    ]
