# Generated by Django 6.0.5 on 2026-05-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='net_income',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='cleaning_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='net_revenue',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='owner_payout',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='pet_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='staykeeper_revenue',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
