# Generated by Django 6.0.5 on 2026-07-21 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_net_income_and_more'),
        ('properties', '0004_property_airbnb_listing_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(max_length=100, unique=True)),
                ('guest_name', models.CharField(max_length=200)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('net_revenue', models.IntegerField()),
                ('cleaning_fee', models.IntegerField(default=0)),
                ('pet_fee', models.IntegerField(default=0)),
                ('reason', models.CharField(choices=[('OVERLAP', 'Solape de fechas'), ('LOW_CLEANING', 'Tarifa de limpieza baja')], max_length=20)),
                ('overlap_group', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada como reserva'), ('cancelled', 'Marcada como cancelada')], default='pending', max_length=20)),
                ('detectado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_bookings', to='properties.property')),
            ],
            options={
                'verbose_name': 'Reserva pendiente de revisión',
                'verbose_name_plural': 'Reservas pendientes de revisión',
                'ordering': ['-detectado_en'],
            },
        ),
    ]
